require("mrbean.plugins-setup")
require("mrbean.core.options")
require("mrbean.core.keymaps")
require("mrbean.core.colorscheme")
require("mrbean.plugins.comment")
require("mrbean.plugins.nvim-tree")
require("mrbean.plugins.lualine")
require("mrbean.plugins.telescope")
